// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200207195153");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "0b999f8e-b5df-4e43-b17d-7ad470f8ff37");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1581586503);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1581586623);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1581586143);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1581675224);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1581586263);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1581586383);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1581586172);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1581586743);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 4725);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1581586112);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 91);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e2dc990f-e3ea-4453-b78b-06b02a0921e7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1581675197978");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1581676981978");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1581675199391");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1581678799391");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200207195153");
user_pref("browser.slowStartup.averageTime", 5209);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200207195153");
user_pref("browser.startup.homepage_override.mstone", "73.0");
user_pref("browser.startup.lastColdStartupCheck", 1581675195);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1581586119927");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "73.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "626ea2c07c1943f58683a6b9ae338e74");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 12 Feb 2020 22:04:54 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1581586504);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "73.0");
user_pref("extensions.lastPlatformVersion", "73.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4ea2d678-c8ba-477d-8449-cace49482727\",\"formautofill@mozilla.org\":\"a7da8a40-24d4-4b87-9832-e995f513faaf\",\"screenshots@mozilla.org\":\"07b7a820-4186-4f23-949d-bf7b5050106d\",\"webcompat-reporter@mozilla.org\":\"eaafb0c5-761e-4f30-a023-a857c897f3fd\",\"webcompat@mozilla.org\":\"e52c21f8-dd6d-494e-acb8-1cc8a411560b\",\"default-theme@mozilla.org\":\"dcac7ec9-b94b-4725-93bb-38d8e2e013b2\",\"google@search.mozilla.org\":\"1b4131bc-925c-4d4f-a86a-cb9bea184277\",\"amazondotcom@search.mozilla.org\":\"5e301900-26f6-406f-b450-30cd9b7acd28\",\"bing@search.mozilla.org\":\"a34e8ede-c035-493d-9a25-64703a1429f3\",\"ddg@search.mozilla.org\":\"3584523b-a050-451f-b6fa-c98b12a1b34d\",\"ebay@search.mozilla.org\":\"ba15acf9-4b87-4a55-ad72-8389685d1580\",\"twitter@search.mozilla.org\":\"e010ffc3-5387-4d53-add2-d10aa44c7bb4\",\"wikipedia@search.mozilla.org\":\"07c0462a-f215-4c2b-a780-d0ad79987b94\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1581586505);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 72516);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c365ce99-a4d7-475e-a7de-787dcc31749e");
user_pref("security.sandbox.plugin.tempDirSuffix", "2d90c368-60bf-448a-be49-b25ab7f20daf");
user_pref("services.settings.clock_skew_seconds", -181);
user_pref("services.settings.last_etag", "\"1581552071874\"");
user_pref("services.settings.last_update_seconds", 1581586563);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1581586563);
user_pref("services.settings.main.cfr-fxa.last_check", 1581586563);
user_pref("services.settings.main.cfr.last_check", 1581586563);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1581586563);
user_pref("services.settings.main.hijack-blocklists.last_check", 1581586563);
user_pref("services.settings.main.language-dictionaries.last_check", 1581586563);
user_pref("services.settings.main.sites-classification.last_check", 1581586563);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1581586563);
user_pref("services.settings.main.whats-new-panel.last_check", 1581586563);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1581675192);
user_pref("toolkit.telemetry.cachedClientID", "3c8a3638-b9d8-4a0e-abe3-80be0d68dc71");
user_pref("toolkit.telemetry.previousBuildID", "20200207195153");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
